project:
  type: website
  output-dir: docs

website:
  title: "Sam Llanwarne's Blog"
  site-url: https://smule11.github.io/Sam-Llanwarne-Blog/
  description: "Sam Llanwarne's blog"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Paper Summaries"
        file: paperSummaries.qmd
      - text: "Academic Formation"
        file: academicFormation.qmd
      - text: "How To"
        file: howTo.qmd
      - text: "Blog"
        file: blog.qmd
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
        
format:
  html:
    theme:
      light: darkly
      dark: flatly
    css: styles.css





