project:
  type: website
  output-dir: docs

website:
  favicon: icons8-b-100.png
  title: "SamLlan Blog"
  site-url: https://smule11.github.io/Sam-Llanwarne-Blog/
  description: "Sam Llanwarne's blog"
  navbar:
    left:
      - text: "Paper Summaries"
        file: paperSummaries.ipynb
      - text: "Academic Formation"
        file: academicFormations.ipynb
      - text: "How To"
        file: howTo.ipynb
      - text: "Blog"
        file: blog.ipynb
    right:
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
        
format:
  html:
    theme:
      light: darkly
      dark: flatly
    css: styles.css

execute:
  freeze: auto



